## 00. Pytorch Fundamentals

**Resources:**
* Resource notebook: [Link](https://www.learnpytorch.io/00_pytorch_fundamentals/)

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print('Pytorch version:', torch.__version__)

Pytorch version: 2.4.0


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [11]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random nnumbers -> look at data -> uodate random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html


In [25]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5764, 0.0637, 0.3151, 0.4123],
        [0.1270, 0.4906, 0.8550, 0.8420],
        [0.0207, 0.2980, 0.8185, 0.9352]])

In [26]:
random_tensor.ndim

2

In [27]:
random_tensor.shape

torch.Size([3, 4])

In [28]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [35]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [37]:
# Create tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [39]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # What datatype is the tensor(e.g. float32 or float16)
    device=None, # What device is your tensor on
    requires_grad=False) # Whether or not to track gradients with this tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [40]:
float_32_tensor.dtype

torch.float32

In [42]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [43]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [44]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [45]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0240, 0.5559, 0.6439, 0.9026],
        [0.5634, 0.8307, 0.8209, 0.6398],
        [0.7330, 0.8190, 0.6207, 0.3395]])

In [47]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.0240, 0.5559, 0.6439, 0.9026],
        [0.5634, 0.8307, 0.8209, 0.6398],
        [0.7330, 0.8190, 0.6207, 0.3395]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [51]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [52]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [53]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [54]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [56]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix mmultiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - http://mathisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** musth match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
*  `(2, 3) @ (3, 2)` -> `(2, 2)`
*  `(3, 2) @ (2, 3)` -> `(3, 3)`

In [58]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f'Equals: {tensor * tensor}')

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [59]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [60]:
# Matrix multiplication by hand
10*10 + 20*20 + 30*30

1400

In [61]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 849 μs, sys: 1.04 ms, total: 1.89 ms
Wall time: 1.09 ms


In [62]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 254 μs, sys: 189 μs, total: 443 μs
Wall time: 373 μs


tensor(1400)

We can see that the function in torch is way faster, so we should always use torch operations.

### One of the most common errors indeep learning: shape errors

In [63]:
# Shapes for matrix multiplication
tensor_A = torch.tensor(
    [[1, 2],
    [3, 4],
    [5, 6]])

tensor_B = torch.tensor(
    [[7, 10],
    [8, 11],
    [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm iis the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [64]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**:
A **transpose** switches the axes or dimensions of a given tensor.

In [65]:
tensor_B.shape

torch.Size([3, 2])

In [66]:
tensor_B.T.shape

torch.Size([2, 3])

In [69]:
# The matrix multiplication operation works when torch.tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above),  tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above),  tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [85]:
# Create a tensor
x = torch.arange(1, 100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [86]:
# FInd the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [87]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [88]:
# Dind the mean - note: the torch.mean() function requires a tensor fo float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [89]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [90]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [91]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensorwhere the minimum value occurs
x.argmin()

tensor(0)

In [92]:
x[0]

tensor(1)

In [93]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of target tensorwhere the maximum value occurs
x.argmax()

tensor(9)

In [94]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [105]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [106]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [107]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [108]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [110]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [111]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [117]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [119]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add extra dimensions with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

# Add extra dimensions with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [122]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [colour_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [124]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [128]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [129]:
# Let's index on out new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [130]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [131]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [132]:
# YOu can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [133]:
# Get all values of 0th and 1st dimensions but only indez 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [134]:
# Get all values of the 0 dimension but only the 1 indez value of 1st and 2nd dimension
x[:, 1, 1]


tensor([5])

In [135]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [138]:
# Index on x to return 9
print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[0, :, 2])

tensor(9)
tensor([3, 6, 9])


# PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()

In [140]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless  specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [141]:
torch.arange(1.0, 8.0).dtype


torch.float32

In [143]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [144]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))

In [145]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility ( trying to take random out of random)

In short, how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again ...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is "flavour" the randomness.

In [146]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4872, 0.2356, 0.7085, 0.1764],
        [0.2743, 0.3488, 0.8858, 0.5868],
        [0.2542, 0.4279, 0.7518, 0.0510]])
tensor([[0.7570, 0.3875, 0.1634, 0.9847],
        [0.2897, 0.3292, 0.3516, 0.6188],
        [0.3922, 0.7537, 0.8006, 0.7114]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [147]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # In Colab the seed affects only to a single line of code
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky

### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU (options to upgrade as well).
2. Use your own GPU - takes a little big of setup and requires the investiment of purchasing a GPU, there's a lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

### 2. Check for GPU access with PyTorch

In [151]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch sice it's capable of runnin compute on the GPU or Cpu, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [149]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [150]:
# Count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [152]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [153]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [154]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy() # warning: we can't use numpy arrays on GPU

array([1, 2, 3])

In [155]:
# To fix the GPU tensor with NumPy issuem we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Extra-curriculum

See exercises for this notebook here: https://learnpytorch.io/00_pytorch_fundamentals/#exercises

In [156]:
import torch

#### 2. Create a random tensor with shape (7,7)

In [158]:
random_tensor = torch.rand(7, 7)

#### 3. Perform a matrix multiplicatiopn on the tensor from 2 with another random tensor with shape (1,7) (hint: you may have to transpose the second tensor)

In [160]:
second_random_tensor = torch.rand(1, 7)
result = torch.matmul(random_tensor, second_random_tensor.T)

#### 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [162]:
torch.manual_seed(0)

#### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed(0)` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed.

In [163]:
torch.cuda.manual_seed(0)

#### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).

In [164]:
torch.manual_seed(1234)
tensor_A = torch.rand(size=(2, 3), device=device)
torch.manual_seed(1234)
tensor_B = torch.rand(size=(2, 3), device=device)

#### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [167]:
result = torch.matmul(tensor_A, tensor_B.T)
result

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

#### 8. Find the maximum and minimum values of the output of 7.

In [168]:
print(f'The minimum value is {result.min()}')
print(f'The maximum value is {result.max()}')

The minimum value is 0.21611443161964417
The maximum value is 0.628727912902832


#### 9. Find the maximum and minimum index values of the output of 7.

In [169]:
print(f'The minimum index value is {result.argmin()}')
print(f'The maximum index value is {result.argmax()}')

The minimum index value is 1
The maximum index value is 3


#### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [173]:
torch.manual_seed(0)
rand_tensor_A = torch.rand(size=(1, 1, 1, 10))
rand_tensor_B = rand_tensor_A.squeeze().squeeze().squeeze()

In [174]:
rand_tensor_A, rand_tensor_A.shape

(tensor([[[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
            0.4556, 0.6323]]]]),
 torch.Size([1, 1, 1, 10]))

In [175]:
rand_tensor_B, rand_tensor_B.shape

(tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
         0.6323]),
 torch.Size([10]))